@isTest
private class SapAltaPedidoTest {
  
  @isTest static void test_method_one() {
    Test.startTest();

    sapAltaPedido.ZSSD_PEDIDO_POS_TAB cls2          = new sapAltaPedido.ZSSD_PEDIDO_POS_TAB();
    sapAltaPedido.Bapiret2 cls3                     = new sapAltaPedido.Bapiret2();
    sapAltaPedido.ZssdPosSfSapTab cls4              = new sapAltaPedido.ZssdPosSfSapTab();
    sapAltaPedido.ZssdPedidoCondTab cls5            = new sapAltaPedido.ZssdPedidoCondTab();
    sapAltaPedido.ZssdPedidoCab cls6                = new sapAltaPedido.ZssdPedidoCab();
    sapAltaPedido.ZSdAltaPedidoResponse_element cls7 = new sapAltaPedido.ZSdAltaPedidoResponse_element();
    sapAltaPedido.ZSSD_PEDIDO_POS cls8              = new sapAltaPedido.ZSSD_PEDIDO_POS();
    sapAltaPedido.ZssdPosSfSap cls10           = new sapAltaPedido.ZssdPosSfSap();
    sapAltaPedido.Bapiret2Tab cls11            = new sapAltaPedido.Bapiret2Tab();
    sapAltaPedido.ZSdAltaPedido_element cls12     = new sapAltaPedido.ZSdAltaPedido_element();
    sapAltaPedido.ZssdPedidoCond cls13          = new sapAltaPedido.ZssdPedidoCond();
    sapAltaPedido.ZssdTextosTab cls14         = new sapAltaPedido.ZssdTextosTab();
    sapAltaPedido.ZssdTextos cls15            = new sapAltaPedido.ZssdTextos();
    sapAltaPedido.Z_SD_ALTA_PEDIDO cls16        = new sapAltaPedido.Z_SD_ALTA_PEDIDO();

    Test.stopTest();
  }
  
}