@isTest
private class SapAltaClienteS4Test {
  
  @isTest static void test_method_one() {
    Test.startTest();

      
    sapAltaClienteS4.TABLE_OF_ZSSD_IN_CLIE_IMPTO cls3                     = new sapAltaClienteS4.TABLE_OF_ZSSD_IN_CLIE_IMPTO();    
    
    
    sapAltaClienteS4.Z_SD_ALTA_CLIENTEResponse_element cls7 = new sapAltaClienteS4.Z_SD_ALTA_CLIENTEResponse_element();
    sapAltaClienteS4.Z_SD_ALTA_CLIENTE cls8 = new sapAltaClienteS4.Z_SD_ALTA_CLIENTE();
   
    
    sapAltaClienteS4.Bapiret2 cls11            = new sapAltaClienteS4.Bapiret2();
    sapAltaClienteS4.TABLE_OF_BAPIRET2 cls111            = new sapAltaClienteS4.TABLE_OF_BAPIRET2();
    
    
    
    sapAltaClienteS4.Z_SD_ALTA_CLIENTE_element cls12     = new sapAltaClienteS4.Z_SD_ALTA_CLIENTE_element();
    sapAltaClienteS4.TABLE_OF_ZSSD_IN_CLIE_CFIS cls1222     = new sapAltaClienteS4.TABLE_OF_ZSSD_IN_CLIE_CFIS();
    
    sapAltaClienteS4.ZSSD_IN_CLIE_IMPTO cls13 = new sapAltaClienteS4.ZSSD_IN_CLIE_IMPTO();
    sapAltaClienteS4.ZSSD_IN_CLIE_CFIS cls14 = new sapAltaClienteS4.ZSSD_IN_CLIE_CFIS();
    sapAltaClienteS4.ZSSD_IN_CLIE_GRAL cls16        = new sapAltaClienteS4.ZSSD_IN_CLIE_GRAL();

    Test.stopTest();
  }
  
}